import { Routes } from '@angular/router';
import { LoginPageComponent } from './pages/login-page/login-page.component';
import { UserHomePageComponent } from './pages/user-home-page/user-home-page.component';
import { AdminHomePageComponent } from './pages/admin-home-page/admin-home-page.component';
import { RegisterPageComponent } from './pages/register-page/register-page.component';
import { ProductDetailsPageComponent } from './pages/product-details-page/product-details-page.component';
import { ProductCreatePageComponent } from './pages/product-create-page/product-create-page.component';
import { ProductsPageComponent } from './pages/products-page/products-page.component';
import { ProfilePageComponent } from './pages/profile-page/profile-page.component';
import { HistoryListPageComponent } from './pages/history-list-page/history-list-page.component';
import { ContactPageComponent } from './pages/contact-page/contact-page.component';
import { SuggestedItemsPageComponent } from './pages/suggested-items-page/suggested-items-page.component';
import { ChefRecipesPageComponent } from './pages/chef-recipes-page/chef-recipes-page.component';
import { ForgotPasswordPageComponent } from './pages/forgot-password-page/forgot-password-page.component';

export const routes: Routes = [
  { path: '', component: LoginPageComponent },
  { path: 'login', component: LoginPageComponent },
  { path: 'register', component: RegisterPageComponent },
  { path: 'forgot-password', component: ForgotPasswordPageComponent },
  { path: 'home', component: UserHomePageComponent },
  { path: 'admin-home', component: AdminHomePageComponent },
  { path: 'details/:id', component: ProductDetailsPageComponent },
  { path: 'create-product', component: ProductCreatePageComponent },
  { path: 'products', component: ProductsPageComponent },
  { path: 'profile', component: ProfilePageComponent },
  { path: 'history-list', component: HistoryListPageComponent },
  { path: 'contact', component: ContactPageComponent },
  { path: 'suggestes-items', component: SuggestedItemsPageComponent },
  { path: 'chef-recipes', component: ChefRecipesPageComponent },
];
